# This is the global configuration
device:
  gpu:              # optional. no need this entry if your machine does not have GPU
    count: 1
    mem_limit: 3    # GB: not used for now. 
  cpu:
    max_threads: 20 # not used for now.
  software:
    os: linux       # windows / linux
logging:
  logger: utils.logging_wandb.LoggerWandB
  dir: 
    local: ../pymarl_zz/logs
  ignore_config_name: 
    - toy.yml
