env: pp

env_args:
  size: 10
  vision: 0
  nagents: 4
  symmetric_agents: True
  moving_prey: False
  nenemies: 1
  no_stay: False
  limit: 45     
  serial_exec: True
  obstacles:  
      random: adjacent 
      num: 1          
      location: none 
      horizontal: none 
      size: 9 
      attn:
        - 4.5         
wifi_args:
  name: wifi #wifi
  constant_file: constants_0616
  comm_type: never 
  msg_type: 
    - hid
    - rss
  embedder_type:
    hid: gin 
    rss: gin
  msg_replay: generated 
  msg_gradient: detach    

test_greedy: True
test_nepisode: 128
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 4050000
