env: pp

env_args:
  size: 10
  vision: 0
  nagents: 3
  symmetric_agents: True
  moving_prey: False
  nenemies: 1
  no_stay: False
  limit: 40     
  serial_exec: True
  obstacles:  #{} 
      random: adjacent  
      num: 1          
      location: none  
      horizontal: none 
      size: 9 
      attn:
        - 4.5           
wifi_args:
  name: wifi
  constant_file: constants_0616
  comm_type: policy   
  msg_type: 
    - hid

  embedder_type:
    hid: gin  
  msg_replay: generated 
  msg_gradient: attach    

test_greedy: True
test_nepisode: 128
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 6550000
